-- 기자
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '송경원' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL ,'이자연 ' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '남선우' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '이유채' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '김경수' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '양지헌' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '김소미' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPOTER_SEQ.NEXTVAL , '정재현' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '조현나' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '유선아' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '송경원' );
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '김신록');
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '임수현');
INSERT INTO REPORTER(REPORTER_SEQ, NAME)
VALUES (REPORTER_SEQ.NEXTVAL , '이주현');
select * from reporter;
commit;

-- 기사
INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'안녕,소룡..','극장가에 멜로 로맨스의...', 1, 1) ;

INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL, ' [해외뉴스]' ,'제 98회 아카데미시상..',2, 2);

INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[기획]영화를..','<극장판 체인소 맨..>', 3, 3);

INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[who are you]..','그룹 오마이걸의 ..', 4, 4) ;

INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[특집]스튜디오..','걸작은 보통 천재 ..', 5, 5);
INSERT INTO ARTICLE  (ARtICLE_SEQ , TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[뉴욕]<파리대왕>에서..','근래보기드문 ..', 6, 6) ;

INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[특집]<극장의무게..>에서..','2025년이 ..', 7, 7) ;

INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[기획]우주 최초의..','동시대일렉토릭..',8, 8) ;

INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[특집]우리가 직면한 중요한..','인공지능..',9, 9 ) ;

INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[비평]파격은 다시..','한때 가장 급..',10, 10 );


INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[씨네스코프][ .', '3D영화의..' ,11, 11) ;


INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[김신록의..]..','책상의..',12,12) ;


INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[기획]극장 위기..','지금은 당장 위기..',13, 13) ;


INSERT INTO ARTICLE  (article_seq, TITLE, CONTENT ,REPORTER_SEQ , movie_seq)
VALUES (ARTICLE_SEQ.NEXTVAL,'[이주현편집장]','올해는 두 글..',13, 14 ) ;




select * from article;
commit;

